module.exports = Object.freeze({
  PLACE_DETAILS_FETCH_START: 'PLACE_DETAILS_FETCH_START',
  PLACE_DETAILS_FETCH_SUCCESS: 'PLACE_DETAILS_FETCH_SUCCESS',
  PLACE_DETAILS_FETCH_FAILED: 'PLACE_DETAILS_FETCH_FAILED',
})
